head_node_type:
  name: head
  instance_type: m5.2xlarge
  resources:
    cpu: 0

worker_node_types:
# 8 vCPU, 1 NVIDIA L4 GPU, 24 GiB memory
- name: gpu-worker
  instance_type: g6.2xlarge
  min_workers: 0
  max_workers: 4
  use_spot: true
  fallback_to_ondemand: true
