head_node_type:
  name: head
  instance_type: m5.2xlarge
  resources:
    cpu: 0
    gpu: 0
worker_node_types:
  - instance_type: g4dn.2xlarge
    min_workers: 1
    max_workers: 1

flags:
  allow-cross-zone-autoscaling: true