head_node_type:
  name: head
  instance_type: m5.2xlarge
worker_node_types:
  - name: worker-gpu
    instance_type: g4dn.2xlarge
    min_workers: 1
    max_workers: 1

flags:
  allow-cross-zone-autoscaling: true