head_node_type:
  name: head
  instance_type: n1-standard-8
worker_node_types:
  - name: worker-cpu
    instance_type: n1-standard-8
    min_workers: 10
    max_workers: 10

flags:
  allow-cross-zone-autoscaling: true