head_node:
  instance_type: g5.4xlarge
  resources:
    CPU: 16
    GPU: 1
  flags: {}
worker_nodes:
  - instance_type: g5.4xlarge
    flags: {}
    name: '1xA10G:16CPU-64GB'
    min_nodes: 1
    max_nodes: 1
    market_type: ON_DEMAND
enable_cross_zone_scaling: false
flags:
  allow-cross-zone-autoscaling: false
