head_node_type:
  name: head_node
  instance_type: g6.4xlarge
  resources:
    cpu: 12
    gpu: 1

worker_node_types:
  - instance_type: g6.4xlarge
    name: '1xL4:16CPU-64GB'
    min_workers: 1
    max_workers: 1

allowed_azs:
  - us-west-2d

flags:
  allow-cross-zone-autoscaling: false
