head_node_type:
  name: head
  instance_type: n2-standard-8
  resources:
    cpu: 0
worker_node_types:
- name: cpu-worker
  instance_type: n2-standard-8
  min_workers: 0
  max_workers: 100
- name: gpu-worker-t4-1
  instance_type: n1-standard-8-nvidia-t4-16gb-1
  resources:
    cpu:
    gpu:
    memory:
    object_store_memory:
    custom_resources:
      "accelerator_type:T4": 1
  min_workers: 0
  max_workers: 100
- name: gpu-worker-l4-1
  instance_type: g2-standard-12-nvidia-l4-1
  resources:
    cpu:
    gpu:
    memory:
    object_store_memory:
    custom_resources:
      "accelerator_type:L4": 1
  min_workers: 0
  max_workers: 100
- name: gpu-worker-l4-2
  instance_type: g2-standard-24-nvidia-l4-2
  resources:
    cpu:
    gpu:
    memory:
    object_store_memory:
    custom_resources:
      "accelerator_type:L4": 1
  min_workers: 0
  max_workers: 100
- name: gpu-worker-l4-4
  instance_type: g2-standard-48-nvidia-l4-4
  resources:
    cpu:
    gpu:
    memory:
    object_store_memory:
    custom_resources:
      "accelerator_type:L4": 1
  min_workers: 0
  max_workers: 100
gcp_advanced_configurations_json:
  instance_properties:
    labels:
      as-feature-multi-zone: 'true'
      as-feature-enable-multi-az-serve: 'true'
