head_node:
  required_resources:
    CPU: 8
    memory: 32Gi
  resources:
    CPU: 0
worker_nodes:
- name: gpu_worker
  required_resources:
    CPU: 8
    memory: 32Gi
    GPU: 1
    accelerator: T4
  min_nodes: 2
  max_nodes: 2
