applications:
- args:
    llm_configs:
    - ./deploy/services/model_config/meta-llama--Meta-Llama-3-8B-Instruct.yaml
  import_path: rayllm:app
  name: llm-endpoint
  route_prefix: /
query_auth_token_enabled: false
