head_node_type:
  name: head_node
  instance_type: m5.2xlarge

worker_node_types:
  - instance_type: g4dn.12xlarge
    min_workers: 2
    max_workers: 2

  - instance_type: r7i.12xlarge
    min_workers: 2
    max_workers: 2

flags:
  allow-cross-zone-autoscaling: true
