head_node_type:
  name: head
  instance_type: m5.2xlarge
  resources:
    cpu: 0
    gpu: 0
worker_node_types:
  - name: 1xL4:16CPU-64GB
    instance_type: g6.4xlarge
    min_workers: 1
    max_workers: 1

flags:
  allow-cross-zone-autoscaling: true