head_node_type:
  name: head
  instance_type: n1-standard-8
  resources:
    cpu: 0
    gpu: 0
worker_node_types:
  - name: 1xL4:16CPU-64GB
    instance_type: g2-standard-16-nvidia-l4-1
    min_workers: 1
    max_workers: 1

flags:
  allow-cross-zone-autoscaling: true
