name: preference-tuning-summarization-summary-generation-finetuned
entrypoint: python -m src.scripts.generate_summaries_and_scores configs/summary_generation/70b_judge/mistral_finetuned_eval.yaml
image_uri: localhost:5555/anyscale/endpoints_aica:1.0.0-7260
max_retries: 0
working_dir: "."
