head_node_type:
  name: head
  instance_type: n2-standard-8
  resources:
    CPU: 0
    GPU: 0
worker_node_types:
- name: gpu-worker
  instance_type: g2-standard-8-nvidia-l4-1
  min_workers: 2
  max_workers: 2

flags:
  allow-cross-zone-autoscaling: true
