head_node_type:
  name: head
  instance_type: m5.2xlarge
  resources:
    cpu: 8

worker_node_types:
- name: cpu-worker
  instance_type: m5.2xlarge
  min_workers: 0
  max_workers: 1
- name: gpu-worker
  instance_type: g5.12xlarge
  min_workers: 0
  max_workers: 2

flags:
  allow-cross-zone-autoscaling: true
