#!/usr/bin/env bash
# Package the toolchain as pip wheels, for running this template on a *stock* Anyscale image
# instead of the custom one the Dockerfile builds.
#
#   usage: build_wheels.sh [OUTDIR]       (default: ./wheelhouse)
#
# Read tools/BUILDING.md before using the result -- the wheels alone are not enough, because
# a job's `requirements:` is installed before its `working_dir` is staged. BUILDING.md covers
# the staging step that makes them resolvable.
#
# This reuses build_tools.sh for the builds, so a wheel contains exactly what the image
# contains: one build path, two delivery formats, one manifest.
#
# Must run on linux x86_64 -- the wheels carry Linux ELF binaries and hatchling tags a
# non-pure wheel from the building platform. The easy way is inside the template's own image:
#
#   docker run --rm -v "$PWD:/w" -w /w <image> bash tools/build_wheels.sh /w/wheelhouse
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MANIFEST="$HERE/manifest.toml"
OUTDIR="${1:-$PWD/wheelhouse}"
STAGE="$(mktemp -d)"
trap 'rm -rf "$STAGE"' EXIT

case "$(uname -s)/$(uname -m)" in
  Linux/x86_64) ;;
  *) echo "FATAL: build on linux x86_64; see the header for the container one-liner" >&2
     exit 1 ;;
esac

mkdir -p "$OUTDIR"

echo "== building the toolchain (shared with the image build)"
bash "$HERE/build_tools.sh" "$STAGE/prefix"

python3 - "$MANIFEST" "$STAGE" "$OUTDIR" <<'PY'
"""Turn each built payload into a wheel.

The layout mirrors what the tools need at run time rather than what is tidy: the payload
tree is installed whole as `shared_data`, because samtools and quast locate their own
lib/ and share/ relative to their executable, and the PATH entries are `shared_scripts`
shims. On an Anyscale image `shared_scripts` land in /home/ray/anaconda3/bin, which is
already first on every Ray worker's PATH -- so `pip install` alone puts a tool on PATH,
with no image build and no ENV surgery.
"""

import os
import shlex
import subprocess
import sys
import tomllib
from pathlib import Path

manifest_path, stage, outdir = (Path(p) for p in sys.argv[1:4])
prefix = stage / "prefix"
with open(manifest_path, "rb") as fh:
    manifest = tomllib.load(fh)["tools"]

DIST_PREFIX = "wdl-on-ray-tools"

SHIM = """#!/bin/sh
# Generated by build_wheels.sh -- resolves the payload relative to this shim's own
# location, so the wheel works wherever the environment happens to be installed.
here=$(cd "$(dirname "$0")" && pwd)
exec "$here/../lib/{dist_prefix}/{tool}/{inside}" "$@"
"""


def build(tool: str, spec: dict) -> None:
    version = spec["version"]
    provides = spec.get("provides", {})
    project = stage / "proj" / tool
    (project / "shims").mkdir(parents=True, exist_ok=True)

    deps: list[str] = []
    shared_data: dict[str, str] = {}
    shared_scripts: dict[str, str] = {}

    if spec["kind"] == "pypi":
        # No payload: the wheel is a dependency edge plus a shim onto what pip installed.
        deps += spec.get("requirements", [])
        deps += [f"{DIST_PREFIX}-{n}" for n in spec.get("needs", [])]
        for on_path, inside in provides.items():
            shim = project / "shims" / on_path
            shim.write_text(f'#!/bin/sh\nexec "$(dirname "$0")/{Path(inside).name}" "$@"\n')
            shim.chmod(0o755)
            shared_scripts[f"shims/{on_path}"] = on_path
    else:
        payload = prefix / "lib" / tool
        if not payload.is_dir():
            raise SystemExit(f"FATAL: {tool} has no payload at {payload}")
        # hatchling cannot store a symlink in a wheel; resolve each to its contents.
        for path in payload.rglob("*"):
            if path.is_symlink():
                target = path.resolve()
                path.unlink()
                if target.is_file():
                    path.write_bytes(target.read_bytes())
                    path.chmod(target.stat().st_mode)
        rel = os.path.relpath(payload, project)
        shared_data[rel] = f"lib/{DIST_PREFIX}/{tool}"
        for on_path, inside in provides.items():
            shim = project / "shims" / on_path
            shim.write_text(SHIM.format(dist_prefix=DIST_PREFIX, tool=tool, inside=inside))
            shim.chmod(0o755)
            shared_scripts[f"shims/{on_path}"] = on_path
        deps += [f"{DIST_PREFIX}-{n}" for n in spec.get("needs", [])]

    def table(mapping: dict[str, str]) -> str:
        return "\n".join(f"{shlex.quote(k)} = {shlex.quote(v)}" for k, v in mapping.items())

    (project / "pyproject.toml").write_text(f"""\
[project]
name = "{DIST_PREFIX}-{tool}"
version = "{version}"
description = "{tool} {version}, packaged for wdl-on-ray"
dependencies = {deps!r}

[build-system]
requires = ["hatchling==1.28.0"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
# Not a pure-Python wheel: it carries Linux ELF binaries, so it must be tagged for the
# platform it was built on rather than py3-none-any.
pure-python = false
bypass-selection = true

[tool.hatch.build.targets.wheel.shared-data]
{table(shared_data)}

[tool.hatch.build.targets.wheel.shared-scripts]
{table(shared_scripts)}
""")

    subprocess.run(
        [sys.executable, "-m", "build", "--wheel", "--outdir", str(outdir), str(project)],
        check=True,
    )


for name, spec in manifest.items():
    print(f"== wheel: {DIST_PREFIX}-{name}")
    build(name, spec)
PY

echo
echo "wheels in $OUTDIR:"
ls -1 "$OUTDIR"
echo
echo "Next: these cannot be installed straight from a job's requirements: -- see tools/BUILDING.md"
