head_node_type:
  instance_type: m5.4xlarge
  name: head_node
  resources:
    cpu: 0
    gpu: 0

worker_node_types:
  - instance_type: g6.4xlarge
    name: '1xL4:16CPU-64GB'
    min_workers: 2
    max_workers: 2

flags:
  allow-cross-zone-autoscaling: true
