head_node_type:
  name: head
  instance_type: m5.2xlarge
worker_node_types:
  - name: worker-cpu
    instance_type: m5.2xlarge
    min_workers: 10
    max_workers: 10

flags:
  allow-cross-zone-autoscaling: true