applications:
- args:
    program_param_path: configs/deploy_params.json
    rayllm_args:
      api_base: https://dspy-rayllm-service-mglb8.cld-tffbxe9ia5phqr1u.s.anyscaleuserdata.com/
      api_key: dummy-key
      route_prefix: /
  import_path: deploy:construct_app
  name: dspy_client
  route_prefix: /classify_intent
  runtime_env:
    pip:
    - dspy
    - matplotlib
    working_dir: .
name: dspy-service
query_auth_token_enabled: false
