context_length: 4096
dataset_size_scaling_factor: 10000
deepspeed:
  config_path: configs/deepspeed/zero_3.json
eval_batch_size_per_device: 8
eval_path: gs://storage-bucket-cld-tffbxe9ia5phqr1unxhz4f7e1e/org_4snvy99zwbmh4gbtk64jfqggmj/cld_tffbxe9ia5phqr1unxhz4f7e1e/artifact_storage/val.json
flash_attention_2: true
learning_rate: 1e-4
lora_config:
  bias: none
  fan_in_fan_out: false
  init_lora_weights: true
  lora_alpha: 16
  lora_dropout: 0.05
  modules_to_save: []
  r: 8
  target_modules:
  - q_proj
  - v_proj
  - k_proj
  - o_proj
  - gate_proj
  - up_proj
  - down_proj
  - embed_tokens
  - lm_head
  task_type: CAUSAL_LM
model_id: meta-llama/Meta-Llama-3.1-70B-Instruct
num_checkpoints_to_keep: 1
num_devices: 32
num_epochs: 10
output_dir: /mnt/local_storage
padding: longest
train_batch_size_per_device: 8
train_path: gs://storage-bucket-cld-tffbxe9ia5phqr1unxhz4f7e1e/org_4snvy99zwbmh4gbtk64jfqggmj/cld_tffbxe9ia5phqr1unxhz4f7e1e/artifact_storage/train.json
trainer_resources:
  memory: 161061273600
valid_path: s3://llm-guide/data/viggo/val.jsonl
worker_resources:
  accelerator_type:L4: 0.001
  memory: 53687091200
