head_node_type:
  name: head
  instance_type: m5.2xlarge
  resources:
    cpu: 0
    gpu: 0
worker_node_types:
  - name: l4-worker
    instance_type: g6.4xlarge
    min_workers: 4
    max_workers: 4
auto_select_worker_config: false
