head_node_type:
  instance_type: n2-standard-8
  resources:
    cpu: 0
    gpu: 0
  flags: {}
enable_cross_zone_scaling: false
auto_select_worker_config: true
idle_termination_minutes: 120
flags:
  allow-cross-zone-autoscaling: false
