model_id: meta-llama/Meta-Llama-3-8B-Instruct # <-- change this to the model you want to fine-tune
# initial_base_model_ckpt_path: ... # <-- Use this if you want to provide a checkpoint for the base-model to start from
initial_adapter_model_ckpt_path: s3://large-dl-models-mirror/finetuning_template/continued_ft_gsm8k_checkpoint # <-- This checkpoint has been fine-tuned on the first half of the gsm8k dataset (s3://large-dl-models-mirror/finetuning_template/train_1.jsonl). Use initial_adapter_model_ckpt_path if you want to provide a checkpoint for the LoRA adapter to start from.
train_path: s3://large-dl-models-mirror/finetuning_template/train_2.jsonl # <-- change this to the path to your training data
valid_path: s3://large-dl-models-mirror/finetuning_template/test.jsonl # <-- change this to the path to your validation data. This is optional
context_length: 512 # <-- change this to the context length you want to use
num_devices: 16 # <-- change this to total number of GPUs that you want to use
num_epochs: 3 # <-- change this to the number of epochs that you want to train for
train_batch_size_per_device: 16
eval_batch_size_per_device: 16
learning_rate: 1e-4 # <-- For LoRA, we recommend to default to 1e-4, for full-parameter training, we recommend 1e-5
padding: "longest" # This will pad batches to the longest sequence. Use "max_length" when profiling to profile the worst case.
num_checkpoints_to_keep: 1
dataset_size_scaling_factor: 10000
output_dir: /mnt/local_storage
deepspeed:
  config_path: deepspeed_configs/zero_3_offload_optim+param.json
dataset_size_scaling_factor: 10000 # internal flag. No need to change
flash_attention_2: true
trainer_resources:
  memory: 53687091200 # 50 GB memory
worker_resources:
  accelerator_type:A10G: 0.001
lora_config:
  r: 8
  lora_alpha: 16
  lora_dropout: 0.05
  target_modules:
    - q_proj
    - v_proj
    - k_proj
    - o_proj
    - gate_proj
    - up_proj
    - down_proj
    - embed_tokens
    - lm_head
  task_type: "CAUSAL_LM"
  modules_to_save: []
  bias: "none"
  fan_in_fan_out: false
  init_lora_weights: true
