name: preference-tuning-summarization-summary-generation-baseline
entrypoint: python -m src.scripts.generate_summaries_and_scores configs/summary_generation/mistral_reference_eval.yaml
image_uri: localhost:5555/anyscale/endpoints_aica:0.5.0-6402
max_retries: 0
working_dir: "."
