head_node_type:
  name: head
  instance_type: n1-standard-8-nvidia-t4-16gb-1
  resources:
    CPU: 0
    GPU: 0
worker_node_types:
- name: 1xL4:8CPU-32GB
  instance_type: g2-standard-8-nvidia-l4-1
  min_workers: 2
  max_workers: 2

flags:
  allow-cross-zone-autoscaling: true
