context_length: 512
dataset_size_scaling_factor: 10000
deepspeed:
  config_path: configs/deepspeed/zero_3_offload_optim+param.json
eval_batch_size_per_device: 16
flash_attention_2: true
generation_config:
  prompt_format:
    assistant: '<|start_header_id|>assistant<|end_header_id|>


      {instruction}<|eot_id|>'
    bos: <|begin_of_text|>
    default_system_message: ''
    system: '<|start_header_id|>system<|end_header_id|>


      {instruction}<|eot_id|>'
    system_in_user: false
    trailing_assistant: '<|start_header_id|>assistant<|end_header_id|>


      '
    user: '<|start_header_id|>user<|end_header_id|>

      {instruction}<|eot_id|>'
learning_rate: 4.5e-05
logger:
  provider: wandb
lora_config:
  bias: none
  fan_in_fan_out: false
  init_lora_weights: true
  lora_alpha: 16
  lora_dropout: 0.05
  modules_to_save: []
  r: 8
  target_modules:
  - q_proj
  - v_proj
  - k_proj
  - o_proj
  - gate_proj
  - up_proj
  - down_proj
  - embed_tokens
  - lm_head
  task_type: CAUSAL_LM
model_id: meta-llama/Llama-3.2-1B-Instruct
num_checkpoints_to_keep: 10
num_devices: 4
num_epochs: 6
output_dir: /mnt/local_storage
padding: longest
train_batch_size_per_device: 32
train_path: gs://storage-bucket-cld-tffbxe9ia5phqr1unxhz4f7e1e/org_4snvy99zwbmh4gbtk64jfqggmj/cld_tffbxe9ia5phqr1unxhz4f7e1e/artifact_storage/trainset_data_banking_2000_formatted.jsonl
valid_path: gs://storage-bucket-cld-tffbxe9ia5phqr1unxhz4f7e1e/org_4snvy99zwbmh4gbtk64jfqggmj/cld_tffbxe9ia5phqr1unxhz4f7e1e/artifact_storage/trainset_val_data_banking_1500_formatted.jsonl
