head_node:
  instance_type: m5.2xlarge
  resources:
    CPU: 0
worker_nodes:
- name: cpu-worker
  instance_type: m5.2xlarge
  max_nodes: 100
- name: gpu-worker-t4-1
  instance_type: g4dn.2xlarge
  resources:
    accelerator_type:T4: 1
  max_nodes: 100
- name: gpu-worker-t4-4
  instance_type: g4dn.12xlarge
  resources:
    accelerator_type:T4: 1
  max_nodes: 100
- name: gpu-worker-a10g-1
  instance_type: g5.4xlarge
  resources:
    accelerator_type:A10G: 1
  max_nodes: 100
- name: gpu-worker-a10g-4
  instance_type: g5.12xlarge
  resources:
    accelerator_type:A10G: 1
  max_nodes: 100
- name: gpu-worker-a10g-8
  instance_type: g5.48xlarge
  resources:
    accelerator_type:A10G: 1
  max_nodes: 100
- name: gpu-worker-v100-1
  instance_type: p3.2xlarge
  resources:
    accelerator_type:V100: 1
  max_nodes: 100
- name: gpu-worker-v100-4
  instance_type: p3.8xlarge
  resources:
    accelerator_type:V100: 1
  max_nodes: 100
- name: gpu-worker-a100-40g-8
  instance_type: p4d.24xlarge
  resources:
    accelerator_type:A100-40G: 1
  max_nodes: 100
  advanced_instance_config:
    BlockDeviceMappings:
    - DeviceName: /dev/sda1
      Ebs:
        DeleteOnTermination: true
        VolumeSize: 1000
- name: gpu-worker-a100-80g-8
  instance_type: p4de.24xlarge
  resources:
    accelerator_type:A100-80G: 1
  max_nodes: 100
  advanced_instance_config:
    BlockDeviceMappings:
    - DeviceName: /dev/sda1
      Ebs:
        DeleteOnTermination: true
        VolumeSize: 1000
