"""Served throughput of the TWO-STAGE composed Serve app (`serve_pipeline_app.py`).

Measures mol/s as a function of **featurizer replica count** with the GPU tier pinned
at one whole L4, which is the question the monolithic `serve_app.py` can't answer: its
replicas each request a GPU slice, so the featurizer count is capped by the GPU node's
vCPU. Here the `Featurizer` deployment requests no GPU, so replicas land on CPU-only
nodes and the two tiers scale independently.

Differences from `scripts/serve_bulk.py` (the monolith driver), all deliberate:
  * Load is generated by N **client actors spread across the cluster**, not one asyncio
    loop on the head node — at these rates a single client process becomes the
    bottleneck and you end up benchmarking the client (the REC-4 trap).
  * Molecules come from the real diverse library (`kmol_divbench/molecules.csv`,
    15,751 unique tox21 + ZINC + ChEMBL-MW800+ structures) rather than a 10-SMILES
    modulo pool. `--pool10` reproduces the old toy set for apples-to-apples comparison
    against the previously published numbers.
  * Capacity is pinned with `request_resources` for the whole sweep so CPU nodes don't
    idle-terminate between points, and the sweep runs high->low so every node installs
    its runtime_env once, up front.

Usage (from the bundle root, detached — see REPRODUCE.md):
    python scripts/serve_pipeline_bulk.py --smoke          # tiny correctness check
    python scripts/serve_pipeline_bulk.py                  # full sweep, real library
    python scripts/serve_pipeline_bulk.py --pool10 --replicas 6
"""
import argparse
import asyncio
import csv
import json
import os
import random
import sys
import time

import ray
from ray import serve
from ray.autoscaler.sdk import request_resources

_BUNDLE = os.environ.get("KMOL_BUNDLE", os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
# Run as `python scripts/serve_pipeline_bulk.py`: sys.path[0] is scripts/, but the app
# module lives at the bundle root. (Replicas get it from the working_dir runtime_env.)
if _BUNDLE not in sys.path:
    sys.path.insert(0, _BUNDLE)
SHIP_DIR = os.environ.get("KMOL_SHIP_DIR", _BUNDLE)
CONFIG = os.environ.get("KMOL_CONFIG", "configs/ensemble_serve.example.json")
CKPT_DIR = os.environ.get("KMOL_CKPT_DIR", "checkpoints")
LIBRARY = os.environ.get("KMOL_LIBRARY", "/home/ray/default/kmol_divbench/molecules.csv")
OUT = os.environ.get("KMOL_OUT", "serve_pipeline_results.json")
APP = "kmolpipe"

TASK_PIP = {"pip": ["torch==2.5.1", "torch_geometric==2.6.1", "rdkit==2024.3.5", "numpy<2"]}

# Old 10-SMILES pool, kept only to reproduce the previously published numbers.
POOL10 = [
    "CCO", "c1ccccc1", "CC(=O)OC1=CC=CC=C1C(=O)O", "CN1C=NC2=C1C(=O)N(C(=O)N2C)C",
    "CC(C)Cc1ccc(cc1)C(C)C(=O)O", "CN1CCC[C@H]1c1cccnc1", "Oc1ccc2CC3C(Cc2c1)C1CCCCC1CC3",
    "Clc1ccccc1C(=O)Nc1ccccc1", "COc1ccc2nc(sc2c1)N", "CC(=O)Nc1ccc(O)cc1",
]

# Measured single-core featurization rates (kmol_divbench/phase1_results.json), used
# only to size each run to a target duration.
PER_CORE_EST = {"library": 131.0, "pool10": 407.0}

INGRESS_REPLICAS = int(os.environ.get("KMOL_INGRESS_REPLICAS", "4"))
SHUFFLE_SEED = int(os.environ.get("KMOL_SHUFFLE_SEED", "0"))


@ray.remote(num_cpus=0.5)
class LoadClient:
    """Open-loop-ish client. Lives on the cluster so the driver isn't the bottleneck."""

    def __init__(self, smiles_pool, offset):
        self._pool = smiles_pool
        self._offset = offset
        self._handle = serve.get_deployment_handle("Ingress", app_name=APP)

    def _chunk(self, i, chunk):
        start = (self._offset + i * chunk) % len(self._pool)
        out = []
        while len(out) < chunk:
            take = self._pool[start:start + (chunk - len(out))]
            if not take:
                start = 0
                continue
            out.extend(take)
            start = (start + len(take)) % len(self._pool)
        return out

    async def run(self, n_chunks, chunk, concurrency):
        sem = asyncio.Semaphore(concurrency)
        lat = []

        async def one(i):
            async with sem:
                t = time.perf_counter()
                await self._handle.predict.remote(self._chunk(i, chunk))
                lat.append(time.perf_counter() - t)

        t0 = time.perf_counter()
        await asyncio.gather(*[one(i) for i in range(n_chunks)])
        return {"wall_s": time.perf_counter() - t0, "mols": n_chunks * chunk, "lat": lat}

    async def warm(self, chunk):
        await self._handle.predict.remote(self._chunk(0, chunk))
        return True


def load_library(path):
    """Load and SHUFFLE the library (fixed seed).

    The CSV is grouped by source — tox21, then ZINC, then ChEMBL MW>800 — so walking it
    in order makes every chunk size-homogeneous and makes each sweep point sample a
    different part of the size distribution. Featurization cost scales with molecule
    size (0.28 ms/heavy atom), so unshuffled chunks produce both huge stragglers and
    throughput numbers that aren't comparable across points. Shuffling once with a fixed
    seed makes every chunk a representative mix and keeps the run reproducible.
    """
    with open(path) as f:
        pool = [row["smiles"] for row in csv.DictReader(f)]
    random.Random(SHUFFLE_SEED).shuffle(pool)
    return pool


def deploy(feat_replicas, gpu_replicas, num_gpus):
    """(Re)deploy the composed app with a fixed featurizer replica count.

    Fixed min==max on both tiers: this measures the scaling curve, so autoscaling
    transients would just add noise. Autoscaling bounds for real deployments live in
    serve_pipeline_app.py / service.yaml.
    """
    import serve_pipeline_app as spa

    feat = spa.Featurizer.options(
        ray_actor_options={"num_cpus": 1, "runtime_env": TASK_PIP},
        autoscaling_config={"min_replicas": feat_replicas, "max_replicas": feat_replicas},
        max_ongoing_requests=2,
    )
    gpu = spa.GpuForward.options(
        ray_actor_options={"num_gpus": num_gpus, "num_cpus": 1, "runtime_env": TASK_PIP},
        autoscaling_config={"min_replicas": gpu_replicas, "max_replicas": gpu_replicas},
        max_ongoing_requests=32,
    )
    # Ingress needs no torch — only json/starlette — so it gets no pip runtime_env.
    # Held constant at INGRESS_REPLICAS across every sweep point: it assembles a dict
    # per molecule, which at several thousand mol/s is enough Python work to bottleneck
    # a single replica. Fixing it keeps featurizer count the only variable.
    ingress = spa.Ingress.options(
        ray_actor_options={"num_cpus": 1},
        autoscaling_config={"min_replicas": INGRESS_REPLICAS, "max_replicas": INGRESS_REPLICAS},
        max_ongoing_requests=256,
    )
    # NB: the ingress sub-chunks by its own KMOL_CHUNK (default 256) inside the replica.
    # Client chunk == that value means one sub-chunk per request; a larger client chunk
    # is split, which is still correct, just coarser at the client.
    app = ingress.bind(feat.bind(gpu.bind(CONFIG, CKPT_DIR)), CONFIG)
    return serve.run(app, name=APP)


def measure(clients, total_mols, chunk, concurrency_per_client):
    n_chunks_total = max(len(clients), total_mols // chunk)
    per_client = max(1, n_chunks_total // len(clients))
    t0 = time.perf_counter()
    parts = ray.get([c.run.remote(per_client, chunk, concurrency_per_client) for c in clients])
    wall = time.perf_counter() - t0
    mols = sum(p["mols"] for p in parts)
    lat = sorted(l for p in parts for l in p["lat"])
    return {
        "mols": mols, "chunk": chunk, "clients": len(clients),
        "concurrency_per_client": concurrency_per_client,
        "wall_s": wall, "mol_s": mols / wall,
        "req_p50_ms": lat[len(lat) // 2] * 1e3,
        "req_p99_ms": lat[min(int(len(lat) * 0.99), len(lat) - 1)] * 1e3,
        "requests": len(lat),
    }


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--smoke", action="store_true", help="tiny correctness check, then exit")
    ap.add_argument("--pool10", action="store_true", help="use the old 10-SMILES pool")
    ap.add_argument("--replicas", type=int, nargs="*", default=None)
    ap.add_argument("--gpus", type=int, default=1)
    ap.add_argument("--chunk", type=int, default=256)
    ap.add_argument("--clients", type=int, default=4)
    ap.add_argument("--duration", type=float, default=12.0, help="target seconds per point")
    ap.add_argument("--out", default=OUT)
    args = ap.parse_args()

    ray.init(address="auto", runtime_env={"working_dir": SHIP_DIR})

    source = "pool10" if args.pool10 else "library"
    pool = POOL10 if args.pool10 else load_library(LIBRARY)
    print(f"molecule source: {source}  n={len(pool)}", flush=True)

    if args.smoke:
        handle = deploy(2, args.gpus, 1.0)
        got = handle.predict.remote(pool[:8] if not args.pool10 else POOL10[:8]).result()
        print(json.dumps({"n_returned": len(got), "first": got[0]}, indent=2)[:800], flush=True)
        single = handle.predict.remote(pool[0]).result()
        n_logits = len(single["logits"])
        finite = all(v == v for v in single["logits"])
        print(f"single: n_logits={n_logits} all_finite={finite} labels={single.get('labels')}", flush=True)
        assert len(got) == 8 and n_logits == 12 and finite, "SMOKE FAILED"
        print("SMOKE OK", flush=True)
        serve.shutdown()
        return

    replicas = args.replicas or [48, 24, 12, 6]
    # Pin capacity for the whole sweep so CPU nodes don't idle-terminate mid-run, and
    # so every node installs its runtime_env during the first (largest) point.
    peak = max(replicas)
    request_resources(bundles=[{"CPU": 1}] * (peak + INGRESS_REPLICAS + args.clients + 4)
                      + [{"GPU": 1, "CPU": 1}] * args.gpus)

    results = []
    clients = None
    try:
        for n in replicas:
            print(f"\n=== featurizer replicas = {n} (GPU tier = {args.gpus} x L4) ===", flush=True)
            t0 = time.perf_counter()
            handle = deploy(n, args.gpus, 1.0)
            print(f"deployed in {time.perf_counter()-t0:.0f}s", flush=True)

            if clients is None:
                clients = [LoadClient.remote(pool, i * 997) for i in range(args.clients)]
            ray.get([c.warm.remote(args.chunk) for c in clients])

            total = max(args.chunk * args.clients, int(n * PER_CORE_EST[source] * args.duration))
            r = measure(clients, total, args.chunk, concurrency_per_client=max(2, (n // args.clients) + 2))
            r["featurizer_replicas"] = n
            r["gpu_replicas"] = args.gpus
            r["mol_s_per_featurizer_core"] = r["mol_s"] / n
            results.append(r)
            print(f"  {r['mol_s']:>10,.0f} mol/s  ({r['mol_s_per_featurizer_core']:.0f}/core)  "
                  f"p50={r['req_p50_ms']:.0f}ms p99={r['req_p99_ms']:.0f}ms  "
                  f"mols={r['mols']:,} in {r['wall_s']:.1f}s", flush=True)
    finally:
        request_resources(bundles=[])

    base = next((r for r in results if r["featurizer_replicas"] == min(replicas)), results[-1])
    out = {
        "app": "serve_pipeline_app (two-stage composed Serve)",
        "molecule_source": source,
        "library_path": None if args.pool10 else LIBRARY,
        "library_n": len(pool),
        "shuffle_seed": SHUFFLE_SEED,
        "chunk": args.chunk,
        "gpu_replicas": args.gpus,
        "load_clients": args.clients,
        "ingress_replicas": INGRESS_REPLICAS,
        "target_duration_s": args.duration,
        "results": results,
        "peak_mol_s": max(r["mol_s"] for r in results),
        "scaling_vs_min_replicas": [
            {"featurizer_replicas": r["featurizer_replicas"],
             "mol_s": r["mol_s"],
             "speedup_vs_base": r["mol_s"] / base["mol_s"],
             "ideal": r["featurizer_replicas"] / base["featurizer_replicas"],
             "efficiency_pct": 100 * (r["mol_s"] / base["mol_s"]) /
                               (r["featurizer_replicas"] / base["featurizer_replicas"])}
            for r in results
        ],
    }
    with open(args.out, "w") as f:
        json.dump(out, f, indent=2)
    print(f"\nPEAK: {out['peak_mol_s']:,.0f} mol/s   wrote {args.out}", flush=True)
    serve.shutdown()


if __name__ == "__main__":
    main()
