head_node_type:
  instance_type: m5.2xlarge
  resources:
    CPU: 0
    GPU: 0
worker_nodes:
  - instance_type: c4.2xlarge
    name: 8CPU-15GB
    min_nodes: 0
    max_nodes: 5
  - instance_type: g5.xlarge
    name: '1xA10G:4CPU-16GB'
    min_nodes: 0
    max_nodes: 10
  - instance_type: g5.12xlarge
    name: '4xA10G:48CPU-192GB'
    min_nodes: 0
    max_nodes: 1
flags:
  allow-cross-zone-autoscaling: true
