head_node_type:
  name: head
  instance_type: m5.2xlarge
  resources:
    CPU: 0
    GPU: 0

worker_node_types:
  - name: "8CPU-15GB"
    instance_type: c4.2xlarge
    min_nodes: 0
    max_nodes: 5
  - name: "1xA10G:4CPU-16GB"
    instance_type: g5.xlarge
    min_nodes: 0
    max_nodes: 10
  - name: "4xA10G:48CPU-192GB"
    instance_type: g5.12xlarge
    min_nodes: 0
    max_nodes: 1

flags:
  allow_cross_zone_autoscaling: true
