head_node_type:
  name: head
  instance_type: m5.2xlarge
  resources:
    CPU: 0
    GPU: 0
worker_nodes:
  - instance_type: c4.2xlarge
    min_nodes: 0
    max_nodes: 5
  - instance_type: g5.xlarge
    min_nodes: 0
    max_nodes: 10
  - instance_type: g5.12xlarge
    min_nodes: 0
    max_nodes: 1
flags:
  allow-cross-zone-autoscaling: true
