name: workspace-tutorial-service
image_uri: anyscale/ray:2.55.1-slim-py313-cu129
compute_config:
  auto_select_worker_config: true
runtime_env:
  working_dir: .
applications:
  - import_path: serve_app:deployment
