head_node_type:
  name: head
  instance_type: g4dn.2xlarge
worker_node_types:
- name: gpu-worker
  instance_type: g5.2xlarge
  min_workers: 2
  max_workers: 2

flags:
  allow-cross-zone-autoscaling: true
