head_node_type:
  name: head
  instance_type: n2-standard-8
auto_select_worker_config: true
worker_node_types: []

gcp_advanced_configurations_json:
  instance_properties:
    disks:
      - boot: true
        auto_delete: true
        initialize_params:
          disk_size_gb: 250
