cloud: your-anyscale-cloud-name
head_node:
  instance_type: m5.2xlarge
  resources:
    CPU: 0
    GPU: 0
worker_nodes:
- instance_type: m5.2xlarge
  name: fixed-workers
  min_nodes: 4
  max_nodes: 4
