head_node_type:
  instance_type: m5.4xlarge
  resources:
    cpu: 0
    gpu: 0
worker_node_types:
  - instance_type: g5.4xlarge
    name: '1xA10G:16CPU-64GB'
    min_workers: 2
    max_workers: 2
enable_cross_zone_scaling: true
