head_node_type:
  name: head
  instance_type: m5.4xlarge
  resources:
    cpu: 0
    gpu: 0

worker_node_types:
  - instance_type: m5.4xlarge
    name: 16CPU-64GB
    min_workers: 1
    max_workers: 1

allowed_azs:
  - us-west-2b

flags:
  allow-cross-zone-autoscaling: false
