head_node_type:
  name: head
  instance_type: n1-standard-8
worker_node_types:
  - instance_type: g2-standard-8-nvidia-l4-1
    min_workers: 2
    max_workers: 2
enable_cross_zone_scaling: false
flags:
  allow-cross-zone-autoscaling: false
