input_folder: s3://air-example-data/preference-tuning-summarization-example/summary_generation_base/train
max_pairs_per_article: 3
train_val_split: 0.02
accuracy_threshold: 3
output_folder: my_user_name/dpo_training_data # <---- replace with your username. Output folder is created in shared artifact storage
