name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v3

      # Setup Python environment
      - uses: actions/setup-python@v3

      # Install dependencies
      - name: Install pre-commit and Jupyter
        run: pip install pre-commit jupyter

      # Run pre-commit hooks
      - name: Run pre-commit hooks
        run: pre-commit run --all-files --verbose
