name: premerge

on:
  pull_request:
  push:
    branches: [main]

concurrency:
  group: premerge-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dev deps
      run: pip install -r requirements-dev.txt

    - name: Run pre-commit
      run: pre-commit run --all-files --verbose

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dev deps
      run: pip install -r requirements-dev.txt

    - name: Build templates
      run: |
        bash ./download_rayapp.sh
        ./rayapp build all

  validate-build-yaml:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - run: pip install -r requirements-dev.txt
    - run: python ci/validate_build_yaml.py

  check-depsets:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Check depsets are up to date
      run: ./update_deps.sh --check
