"""
E-Commerce Recommendation System — Streamlit Frontend
======================================================

Lets you upload a product image and see the top-5 recommended products
returned by the Ray Serve endpoint.

Run locally (while serve_app is running):
    streamlit run streamlit_app.py

Environment variables:
    SERVE_URL   Base URL of the Ray Serve service  (default: http://localhost:8000)
"""

import base64
import io
import os

import requests
import streamlit as st
from PIL import Image

# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------

SERVE_URL = os.environ.get("SERVE_URL", "http://localhost:8000")
RECOMMEND_ENDPOINT = f"{SERVE_URL}/recommend"
HEALTH_ENDPOINT = f"{SERVE_URL}/health"

st.set_page_config(
    page_title="Product Recommender",
    page_icon="🛍️",
    layout="wide",
)

# ---------------------------------------------------------------------------
# Sidebar
# ---------------------------------------------------------------------------

with st.sidebar:
    st.subheader("Service Status")
    try:
        resp = requests.get(HEALTH_ENDPOINT, timeout=3)
        if resp.ok:
            st.success("✅ Service online")
        else:
            st.error(f"❌ Service returned {resp.status_code}")
    except Exception as e:
        st.warning(f"⚠️ Cannot reach service:\n{e}")

    st.markdown("---")
    st.markdown(f"**Endpoint:** `{RECOMMEND_ENDPOINT}`")
    top_k = st.slider("Number of recommendations", min_value=1, max_value=10, value=5)

    st.markdown("---")
    st.markdown(
        "**How it works**\n\n"
        "1. BLIP captions the image\n"
        "2. Fine-tuned MiniLM embeds the caption\n"
        "3. Cosine search over the product catalog"
    )

# ---------------------------------------------------------------------------
# Header
# ---------------------------------------------------------------------------

st.title("🛍️ E-Commerce Product Recommender")
st.markdown(
    "Upload a product image — the system captions it with **BLIP**, embeds the "
    "caption with a **fine-tuned MiniLM**, and returns the most similar products."
)

# ---------------------------------------------------------------------------
# Image upload
# ---------------------------------------------------------------------------

col_upload, col_preview = st.columns([1, 1], gap="large")

with col_upload:
    st.subheader("Query Image")
    uploaded = st.file_uploader(
        "Choose an image (JPG / PNG)",
        type=["jpg", "jpeg", "png"],
        label_visibility="collapsed",
    )

    if uploaded is None:
        st.info("No image uploaded — using a demo product image.")
        from utils import get_product_image, PRODUCTS
        demo_arr = get_product_image(PRODUCTS[0])  # Wireless Headphones
        buf = io.BytesIO()
        Image.fromarray(demo_arr).save(buf, format="JPEG")
        image_bytes = buf.getvalue()
    else:
        image_bytes = uploaded.read()

    display_image = Image.open(io.BytesIO(image_bytes)).convert("RGB")
    st.image(display_image, use_container_width=True)

    run = st.button("🔍 Find Similar Products", type="primary", use_container_width=True)

# ---------------------------------------------------------------------------
# Call the service
# ---------------------------------------------------------------------------

with col_preview:
    st.subheader("Results")

    if run:
        with st.spinner("Analysing image and searching catalog …"):
            encoded = base64.b64encode(image_bytes).decode("utf-8")
            try:
                resp = requests.post(
                    RECOMMEND_ENDPOINT, json={"image_base64": encoded}, timeout=60
                )
                resp.raise_for_status()
                result = resp.json()
            except requests.exceptions.ConnectionError:
                st.error(
                    "Could not connect to the service. "
                    "Make sure `serve run serve_app:app` is running."
                )
                st.stop()
            except Exception as e:
                st.error(f"Request failed: {e}")
                if hasattr(e, "response") and e.response is not None:
                    st.code(e.response.text)
                st.stop()

        # Caption — shown prominently so viewers understand what drove the results
        caption = result.get("caption", "(no caption)")
        st.markdown("**Caption generated by BLIP:**")
        st.info(f'"{caption}"')

        st.markdown(f"**Top-{top_k} recommendations:**")
        recs = result.get("recommendations", [])[:top_k]
        if not recs:
            st.warning("No recommendations returned.")
        else:
            for rec in recs:
                sim = rec["similarity"]
                st.markdown(
                    f"**{rec['rank']}. {rec['name']}** &nbsp; `{rec['category']}`"
                )
                st.progress(
                    sim,
                    text=f"Similarity: {sim:.1%}",
                )
            st.caption(f"Product IDs: {', '.join(r['product_id'] for r in recs)}")
    else:
        st.markdown("*Upload an image and click **Find Similar Products** to see results.*")

# ---------------------------------------------------------------------------
# Footer
# ---------------------------------------------------------------------------

st.markdown("---")
st.caption(
    "Built with [Ray Serve](https://docs.ray.io/en/latest/serve/index.html), "
    "[BLIP](https://huggingface.co/Salesforce/blip-image-captioning-base), "
    "and [Sentence-Transformers](https://www.sbert.net/) on Anyscale."
)
